App was created
Artem-user-19/todo_list_new pull request #1
Opened 2024-09-06 15:04 UTC by Artem-user-19

2024-09-06 15:42 UTC, viktoria-rybenchuk requested changes
Remove db.sqlite3 and. pychache from the repository

2024-09-06 15:42 UTC, viktoria-rybenchuk commented on todo/forms.py
> +from .models import Task, Tag
[fix imports ](https://peps.python.org/pep-0008/#imports)

2024-09-06 15:42 UTC, viktoria-rybenchuk commented on todo/urls.py
> +]
add a blank line

2024-09-06 15:42 UTC, viktoria-rybenchuk commented on todo/urls.py
> +    # Task URLs
remove redundant comment

2024-09-06 15:42 UTC, viktoria-rybenchuk commented on todo/urls.py
> +    # Tag URLs
the same here

2024-09-06 15:42 UTC, viktoria-rybenchuk commented on todo/urls.py
> +)
place each import on a new line and use absolute imports

2024-09-06 15:42 UTC, viktoria-rybenchuk commented on todo/views.py
> +
use class base view

2024-09-07 11:32 UTC, pavlopro requested changes

2024-09-07 11:32 UTC, pavlopro commented on todo/forms.py
> +from .models import Task, Tag
use absolute import instead of relative

2024-09-07 11:32 UTC, pavlopro commented on todo/urls.py
> +from django.urls import path
Add blank line between different import groups

use absolute import instead of relative

2024-09-07 11:32 UTC, pavlopro commented on todo/views.py
> +from .forms import TaskForm, TagForm
Add blank line between different import groups

use absolute import instead of relative

2024-09-08 10:41 UTC, pavlopro requested changes

2024-09-08 10:41 UTC, pavlopro commented on todo/forms.py
> +from .models import Task, Tag
not resolved

2024-09-08 10:41 UTC, pavlopro commented on todo/models.py
> +from django.db import models
double import

2024-09-14 09:34 UTC, closed without merging

2024-09-17 14:46 UTC, LLkaia reviewed
PR is close, is it expected?